### ISSUE TITLE
Error occurs when I introduce dependency

### ISSUE THREAD

**Issue by yangwenjuan6** [ONLYOFFICE/document-editor-react#13]
The entrypoint for '@onlyoffice/document-editor-react' could not successfully be resolved. The file '/turbo_modules/@onlyoffice/document-editor-react@1.3.0/dist/cjs/index.js' does not exist. Please log an issue with the package author or check for an updated version of the package.

**Comment by aleksandrfedorov97** [comment]
Hi [yangwenjuan6](https://github.com/yangwenjuan6), could you provide more information please. In what type of project are you trying to import the dependency. It would be great if you could provide an example where this error is reproduced.

**Comment by jmmccota** [comment]
@aleksandrfedorov97 same here when I try

```typescript
import { DocumentEditor } from '@onlyoffice/document-editor-react';
import * as React from 'react';
import './style.css';

var onDocumentReady = function (event) {
  console.log('Document is loaded');
};

export default function App() {
  return (
    <div>
      <DocumentEditor
        id="docxEditor"
        documentServerUrl="http://localhost/"
        config={{
          document: {
            fileType: 'docx',
            key: 'Khirz6zTPdfd7',
            title: 'Example Document Title.docx',
            url: 'https://example.com/url-to-example-document.docx',
          },
          documentType: 'word',
          editorConfig: {
            callbackUrl: 'https://example.com/url-to-callback.ashx',
          },
        }}
        events_onDocumentReady={onDocumentReady}
      />
    </div>
  );
}
```

**Comment by aleksandrfedorov97** [comment]
[jmmccota](https://github.com/jmmccota), could you provide an example project where this problem is reproduced?

**Comment by aleksandrfedorov97** [comment]
This issue was closed due to no response.
