### ISSUE TITLE
How to add plugins ? 

### ISSUE THREAD

**Issue by evrardts** [ONLYOFFICE/document-editor-react#21]
How can I add plugins to my word or excel editor using onlyoffice/document-editor-react ? 

I am for example in implementing this one: https://api.onlyoffice.com/plugin/events/oncontextmenuclick?_ga=2.30114047.1787060522.1693813504-2104058758.1683100121

Thanks !

**Comment by SergeyKorneyev** [comment]
You can use the "plugins" section of the editor initialization config: https://api.onlyoffice.com/editors/config/editor/plugins. More information on adding plugins this way is available here: https://api.onlyoffice.com/plugin/installation/onpremises#config.
