### ISSUE TITLE
How do I display the Close button in the top right corner

### ISSUE THREAD

**Issue by ThorSmallice** [ONLYOFFICE/document-editor-react#22]
![image](https://github.com/ONLYOFFICE/document-editor-react/assets/70561783/ec155861-75a4-4314-bf01-2055bdf7b03e)

**Comment by LinneyS** [comment]
You must specify a [goback](https://api.onlyoffice.com/editors/config/editor/customization#goback) field or define a [onRequestClose](https://api.onlyoffice.com/editors/config/events#onRequestClose) event
