### ISSUE TITLE
我接入document-editor-react后，工程报错

### ISSUE THREAD

**Issue by liaoziwei** [ONLYOFFICE/document-editor-react#6]
按照readMe中安装了document-editor-react，页面引入后，工程报Module not found: Error: Cannot resolve module'@onlyoffice/document-editor-react' in .......
onlyoffice对react版本有要求吗？有没有人遇到过相同的问题

**Comment by SergeyKorneyev** [comment]
Hello,
Could you describe the issue in English and in more detail?

**Comment by aleksandrfedorov97** [comment]
This issue was closed due to no response.
